### PR TITLE
added a reference to a snippets package for Atom

### PR DESCRIPTION
**Pull request by jmiazga**

### CODE REVIEW

**Comment by johnpapa** [comment]
controller and directive's controller should not have `/*jshint validthis: true */` but should force starting with an Uppercase letter. Can you do this and then I will merge.

**Comment by johnpapa** [comment]
dependencies should be the same variable too. see controller https://atom.io/packages/angularjs-styleguide-snippets

**Comment by jmiazga** [comment]
I removed the jshint comments. I am unable to force casing in the snippet definition though. Also combined dependency placeholders.

**Comment by johnpapa** [comment]
cool. thanks

**Pull request merged**
