### PR TITLE
Russian translation added

### PR DESCRIPTION
**Pull request by mazhekin**
Hi John, I am very interesting with your style-guide. And I have submitted to you the Russian version of your document. Thanks for your courses, these are very helpful in my work. I am also translating the articles here (codehint.ru) for Russian  audience to help learn AngularJS, and ASP.NET MVC.

### CODE REVIEW

**Comment by johnpapa** [comment]
looks good, thanks for the efforts.

i noticed this is a bit outdated as i have added more material. would you consider updating this to have the latest text?

**Comment by mazhekin** [comment]
Ok. I have started translating 16 days ago. I will compare and add the missing text

**Comment by mazhekin** [comment]
Ок, John. It`s done. I found three new sections.

**Comment by johnpapa** [comment]
thanks

**Pull request merged**
